-- Migration: Add `code` column to items
-- Description: Preserves the legacy human-readable item code (e.g. "MY-Z9UGC")
--              that historically lived in the `id` field. The `id` column
--              remains the UUID primary key (auto-generated by Supabase);
--              `code` stores the original label/code for display and search
--              when a JSON backup with custom string IDs is imported.

-- 1) Add the `code` column (idempotent, in case it already exists)
ALTER TABLE items
  ADD COLUMN IF NOT EXISTS code TEXT;

-- 2) Index for fast lookups / filtering by code
CREATE INDEX IF NOT EXISTS idx_items_code ON items(code);